module.exports={
    "connectionLimit":50,
    "host":"dalog.cd8bwymbnzsj.ap-northeast-2.rds.amazonaws.com",
    "port":"3306",
    "user":"daloguser",
    "password":"dalog1234!",
    "database":"dalogdb",
    "dateStrings":"date"
}